dist:
  - trusty

language:
  - python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10

branches:
  only:
    - master
    - develop

install:
  - pip install tox-travis flake8 nose coverage
  - pip install -r requirements.txt

script:
  - tox

after_success:
  - tox -e coverage
  - tox -e pep8

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/22d93f0e0b577b5583b3
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
